apiVersion: v1
kind: Service
metadata:
  name: pizzabaker
  labels:
    app: pizza-sample
spec:
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: pizzabaker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pizzabaker
  labels:
    app: pizzabaker
    deployment: v4a
spec:
  replicas: 4   # we need more workers 
  template:
    metadata:
      name: pizzabaker
      labels:
        app: pizzabaker
    spec:
      nodeSelector:
        environment: staging
      containers:
        - name: pizzabaker
          image: jensg/pizzabaker:v4-linux
          imagePullPolicy: IfNotPresent   # "Always" is helpful for debugging, but produces traffic
          ports:
            - containerPort: 9091
          env:
            - name: PIZZABAKER_READINESS_PORT
              value: "9081"
            - name: DATABASE_TYPE
              value: Cassandra


