version: "3.3"
    
services:
    cassandra:
        image: cassandra
        networks:
            - connection
        volumes:
            - cassandra:/var/lib/cassandra 
        deploy:
            placement:
                constraints: 
                    - node.labels.pizza == frontend
        
    pizzeria:
        image: pizzeria:v4-linux
        build: 
            context: Pizzeria/
        networks:
            - connection
        ports:
            - "80:80"  # check IP with "docker inspect pizza_connection"
        depends_on:
            - cassandra
        deploy:
            update_config:
                parallelism: 2
                delay: 15s
            resources:
                limits:
                    cpus: '0.40'
            placement:
                constraints: 
                    - node.labels.pizza == frontend
            
    pizzabaker:
        image: pizzabaker:v4-linux
        build: 
            context: PizzaBaker/
        networks:
            - connection
        depends_on:
            - pizzeria
        deploy:
            mode: replicated
            replicas: 10
            placement:
                constraints: 
                    - node.labels.pizza == backend

networks:
    connection:
        driver: "overlay"

volumes:
    cassandra:
