apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: pizza-sample
spec:
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassandra
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
    deployment: v4a
spec:
  replicas: 1
  template:
    metadata:
      name: cassandra
      labels:
        app: cassandra
    spec:
      nodeSelector:
        environment: staging
      containers:
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: "500m"
              memory: 3Gi
            requests:
              cpu: "500m"
              memory: 1Gi
      
        
